# Generated by Django 5.2.5 on 2025-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageManagement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message_subject",
                    models.CharField(
                        help_text="Краткий заголовок письма, отображается в поле «Тема» у получателя.",
                        max_length=255,
                        verbose_name="Тема письма",
                    ),
                ),
                ("body", models.TextField(help_text="Содержание письма.", verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["message_subject"],
            },
        ),
    ]
