# Generated by Django 5.2.5 on 2025-09-04 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_crm", "0001_initial"),
        ("messages_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Created", "Создана"), ("Started", "Запущена"), ("Completed", "Завершена")],
                        default="Created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_mailings",
                        to="messages_mgmt.messagemanagement",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="recipient_mailings",
                        to="customer_crm.mailingrecipient",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-start_datetime"],
            },
        ),
    ]
