# Generated by Django 5.2.5 on 2025-09-06 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0002_alter_mailing_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата и время первой отправки"),
        ),
        migrations.CreateModel(
            name="AttemptMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "time_attempt",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата и время попытки"),
                ),
                (
                    "Mail_server_sesponse",
                    models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing_list.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["-time_attempt"],
            },
        ),
    ]
