# Generated by Django 5.2.5 on 2025-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0003_alter_mailing_end_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attemptmailing",
            old_name="Mail_server_sesponse",
            new_name="mail_server_response",
        ),
        migrations.AddField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("Successfully", "Успешно"), ("Not successful", "Не успешно")],
                default="Successfully",
                max_length=20,
                verbose_name="Статус отправки",
            ),
        ),
    ]
