# Generated by Django 5.2.6 on 2025-09-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0004_rename_mail_server_sesponse_attemptmailing_mail_server_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("SUCCESS", "Успешно"), ("FAILURE", "Не успешно")],
                default="SUCCESS",
                max_length=20,
                verbose_name="Статус отправки",
            ),
        ),
    ]
