# Generated by Django 5.2.6 on 2025-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0005_alter_attemptmailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptmailing",
            options={
                "ordering": ["-time_attempt"],
                "permissions": [("view_mailing_stats", "view mailing stats")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failure", "Не успешно")],
                default="success",
                max_length=20,
                verbose_name="Статус отправки",
            ),
        ),
    ]
