# Generated by Django 5.2.6 on 2025-09-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0008_mailing_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptmailing",
            options={
                "ordering": ["-time_attempt"],
                "permissions": [("view_mailing_stats", "view mailing stats"), ("disable_mailing", "disable mailing")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
