# Generated by Django 5.2.6 on 2025-09-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0010_alter_attemptmailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptmailing",
            options={
                "ordering": ["-time_attempt"],
                "permissions": [("view_mailing_stats", "view mailing stats")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_datetime"],
                "permissions": [("disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
