# Generated by Django 5.2.6 on 2025-09-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0011_alter_attemptmailing_options_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
