# Generated by Django 5.2.6 on 2025-09-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0012_mailing_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptmailing",
            options={
                "ordering": ["-time_attempt"],
                "permissions": [
                    ("view_mailing_stats", "view mailing stats"),
                    ("disable_mailing", "Can disable mailing"),
                    ("view_mailing", "Can view mailing"),
                    ("view_mailingrecipient", "Can view mailing recipients"),
                    ("view_customuser", "Can view users"),
                    ("block_user", "Can block users"),
                ],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
