# Generated by Django 5.2.6 on 2025-09-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_confirmation_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": [("block_user", "block user")]},
        ),
    ]
