# Generated by Django 5.2.6 on 2025-09-13 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_crm", "0003_alter_mailingrecipient_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mailingrecipient",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name="E-Mail Address"
            ),
        ),
    ]
