# Generated by Django 5.2.6 on 2025-09-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_crm", "0004_alter_mailingrecipient_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["email"],
                "permissions": [("view_all_mailingrecipient", "Может просматривать всех получателей")],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
    ]
