# Generated by Django 5.2.6 on 2025-09-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_crm", "0005_alter_mailingrecipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["email"],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
    ]
